# https://taskfile.dev

version: '3'

tasks:
  default:
    aliases:
      - format
    cmds:
      - isort .
      - isort notebooks/
      - black .
      - black notebooks/
    silent: true
    deps:
      - lint
  lint:
    cmds:
      - ruff . --fix --ignore E501
      
  lint-notebooks:
    cmds:
      - ruff notebooks/*.ipynb --fix --ignore E501
  test:
    cmds:
      - pytest -vs -m "not integration"
    
  type:
    cmds:
      - pyright